name = "egypt-tech-scene"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "egypt-tech-scene-d1-prod"
database_id = "bc5130fe-1178-4d30-a478-098b6c4c1345"

# [ai]
# binding = "AI"

[placement]
mode = "smart"