name = "egypt-tech-scene"
compatibility_date = "2023-12-01"

main = "src/index.ts"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "egypt-tech-scene-d1-prod"
database_id = "bc5130fe-1178-4d30-a478-098b6c4c1345"

[placement]
mode = "smart"